using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;

namespace BeastScam.SourceGen;


// First attempt at this thing
[Generator]
internal class BeastScam : ISourceGenerator
{
	public void Execute(GeneratorExecutionContext context)
	{
		var filePaths = context.AdditionalFiles
			.Where(file => string.Equals(Path.GetExtension(file.Path), ".png", StringComparison.OrdinalIgnoreCase))
			.Select(file => Path.GetFullPath(file.Path))
			.Where(file => file.Contains("Content"))
			.Distinct()
			.OrderBy(path => path, StringComparer.Ordinal)
			.ToArray();
		var soundPaths = context.AdditionalFiles
			.Where(file => string.Equals(Path.GetExtension(file.Path), ".ogg", StringComparison.OrdinalIgnoreCase))
			.Select(file => Path.GetFullPath(file.Path))
			.Where(file => file.Contains("Content"))
			.Distinct()
			.OrderBy(path => path, StringComparer.Ordinal)
			.ToArray();
		var sb = new StringBuilder();
		sb.AppendLine("// This class is auto-generated by BeastScam.SourceGen");
		sb.AppendLine("using Microsoft.Xna.Framework.Graphics;");
		sb.AppendLine("using ReLogic.Content;");
		sb.AppendLine("using Terraria.ModLoader;");
		sb.AppendLine("using Terraria.Audio;");
		sb.AppendLine("namespace BeastScam.Core;");
		sb.AppendLine("internal static class GeneratedSource");
		sb.AppendLine("{");
		foreach (string path in filePaths)
		{
			int index = path.IndexOf("BeastExitScamMod", StringComparison.OrdinalIgnoreCase);
			string processedPath = index >= 0 ? path.Substring(index) : path;
			processedPath = processedPath.Replace("\\", "/");
			if (processedPath.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
			{
				processedPath = processedPath.Substring(0, processedPath.Length - 4);
			}
			sb.AppendLine($"    public static Asset<Texture2D> {Path.GetFileName(processedPath)} = ModContent.Request<Texture2D>(\"{processedPath}\", AssetRequestMode.ImmediateLoad);");
		}
		foreach (string soundPath in soundPaths)
		{
			int index = soundPath.IndexOf("BeastExitScamMod", StringComparison.OrdinalIgnoreCase);
			string processedPath = index >= 0 ? soundPath.Substring(index) : soundPath;
			processedPath = processedPath.Replace("\\", "/");
			if (processedPath.EndsWith(".ogg", StringComparison.OrdinalIgnoreCase))
			{
				processedPath = processedPath.Substring(0, processedPath.Length - 4);
			}
			sb.AppendLine($"    public static SoundStyle {Path.GetFileName(processedPath)} = new(\"{processedPath}\")");
			sb.AppendLine("    {");
			sb.AppendLine("        Volume = 0.4f,");
			sb.AppendLine("        PitchVariance = 0.5f,");
			sb.AppendLine("        Type = SoundType.Sound");
			sb.AppendLine("    };");
		}
		sb.AppendLine("}");
		context.AddSource("GeneratedSource.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
	}
	public void Initialize(GeneratorInitializationContext context)
	{

	}
}
